server:
  port: 9004

spring:
  application:
    name: search-service
  elasticsearch:
    uris: http://192.168.100.128:9200
    connection-timeout: 60s
    socket-timeout: 60s
  cloud:
    nacos:
      discovery:
        enabled: false
        server-addr: 192.168.100.128:8848
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

logging:
  level:
    com.campus: debug
    org.springframework.data.elasticsearch: debug 