server:
  port: 9002

spring:
  application:
    name: course-service
  datasource:
    url: jdbc:mysql://192.168.100.128:3306/campus?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.100.128
    port: 6379
    password: 123456
  cloud:
    nacos:
      discovery:
        enabled: false
        server-addr: 192.168.100.128:8848

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.campus.course.entity

logging:
  level:
    com.campus: debug 