server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        enabled: false
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: user-service
          uri: http://localhost:9001
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=0
        - id: course-service
          uri: http://localhost:9002
          predicates:
            - Path=/api/course/**
          filters:
            - StripPrefix=0
        - id: score-service
          uri: http://localhost:9003
          predicates:
            - Path=/api/score/**
          filters:
            - StripPrefix=0
        - id: search-service
          uri: http://localhost:9004
          predicates:
            - Path=/api/search/**
          filters:
            - StripPrefix=0

logging:
  level:
    com.campus: debug 