server:
  port: 9001

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://mysql:3306/campus?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: redis
    port: 6379
    password: 123456
  cloud:
    nacos:
      discovery:
        enabled: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.campus.user.entity

logging:
  level:
    com.campus: debug 